### ISSUE TITLE
Cannot resolve artifact

### ISSUE THREAD

**Issue by kjkrum** [savvyapps/ToggleButtonLayout#1]
I'm trying to use the Java version of the library. The docs say to use

    implementation 'com.github.savvyapps:ToggleButtonLayout:latest.version.here'

Examining the source to find the version number, it looks like that should actually be

    implementation 'com.savvyapps:togglebuttonlayout:1.0'

But gradle cannot resolve version 1.0 of either of those artifacts. What is the latest artifact, version, and repository information?

**Comment by Jawnnypoo** [comment]
Hey there @kjkrum 

The latest version is 1.0.0, the JitPack badge at the top of the README is where to find this. 

For Java support, it would be something more like this though:
```
implementation 'com.github.savvyapps:ToggleButtonLayout:java-SNAPSHOT'
```
to use the latest on the Java branch 😄
