### ISSUE TITLE
Remove toggle buttons programatically?

### ISSUE THREAD

**Issue by frapeti** [savvyapps/ToggleButtonLayout#12]
I couldn't find any way to do it

**Comment by pedrofsn** [comment]
@frapeti do you know how can I add toglle buttons programatically?

**Comment by pedrofsn** [comment]
I found a method! 
`addToggle(toogle)`

**Comment by Hub2018** [comment]
Like @pedrofsn suggets, the best approach is to use addToggle to create the buttons dynamically as it is not possible to hide them.

**Comment by Jawnnypoo** [comment]
Yep, I tried out adding a `removeToggle` method, but there are lots of complications with removing the correct divider associated with the toggles. I think it is indeed best to instead add the buttons you need and omit the ones you don't.
