### ISSUE TITLE
ToggleListener

### ISSUE THREAD

**Issue by KelvinPac** [savvyapps/ToggleButtonLayout#13]
I tried setting a listener so as to get Toggle events using 

```
> toggleButtonLayout.setOnToggleSelectedListener(new ToggleButtonLayout.OnToggledListener() {
>             @Override
>             public void onToggled(Toggle toggle, boolean selected) {
> 
>             }
>         });
```

 but this method doesn't resolve. Am using Java

**Comment by KelvinPac** [comment]
So I was able to get the listener working after some very stressful moments. I actually don't know what this piece of code does but it works. It is nowhere in your documentation or in the samples. The samples don't work
`toggleSwitch.setOnToggledListener(new Function2<Toggle, Boolean, Unit>() {
            @Override
            public Unit invoke(Toggle toggle, Boolean aBoolean) {
                return null;
            }
        });`

**Comment by Jawnnypoo** [comment]
Hey there @KelvinPac, we wrote all the documentation and samples in Kotlin and the listener is a Kotlin Lambda, which causes this interesting callback listener in Java. If someone else has this issue, we can point them to this issue now, so thanks!

**Comment by KelvinPac** [comment]
Welcome,
Cheers

**Comment by Eimert** [comment]
As of release 1.3.0 the setOnToggledListener() above by @KelvinPac needs a minor adjustment: 
&nbsp;&nbsp;new Function**3**

Full code (works for me):
```java
        setToggle.setOnToggledListener(new Function3<ToggleButtonLayout, Toggle, Boolean, Unit>() {
            @Override
            public Unit invoke(ToggleButtonLayout toggleButtonLayout, Toggle toggle, Boolean aBoolean) {
                zeroChanges = false;
                return null;
            }
        });
```

The same example using a Lambda expression:
```java
        setToggle.setOnToggledListener((ToggleButtonLayout toggleButtonLayout, Toggle toggle, Boolean aBoolean) -> {
            zeroChanges = false;
            return null;
        });
```

GL ;)
