### ISSUE TITLE
How to check, which button has been pressed?

### ISSUE THREAD

**Issue by PrashantYadav** [savvyapps/ToggleButtonLayout#2]
I want to perform some action when one particular button is pressed. I'm using below code, but don't know what to do next.

        ToggleButtonLayout toggleButtonLayout = (ToggleButtonLayout) findViewById(R.id.toggleText);
        List<Toggle> selectedToggles = toggleButtonLayout.getSelectedToggles();

**Comment by Jawnnypoo** [comment]
Good question! This is covered a bit in the sample `app` module, but it looks like you are using this library from within a Java app. This will look a bit like this:
```java
toggleButtonLayout.setOnToggledListener(new Function2<Toggle, Boolean, Unit>() {
            @Override
            public Unit invoke(Toggle toggle, Boolean selected) {
                switch (toggle.getId()) {
                    //do something for each case
                }
                return Unit.INSTANCE;
            }
});
```
It can look pretty strange, since it is a Kotlin Lambda from within a Java context, but hopefully that makes sense.
