### ISSUE TITLE
how to change selected color and unselected color

### ISSUE THREAD

**Issue by Miteshmakwana73** [savvyapps/ToggleButtonLayout#5]
how to change selected color and unselected color

**Comment by abdallahMurad** [comment]
+1

**Comment by Jawnnypoo** [comment]
Sure, see https://github.com/savvyapps/ToggleButtonLayout/issues/6 for changing selected, or take a look at the sample project. Additionally, you can control the way the unselected color looks by changing the background of the layout, which you can control using the layout attribute in XML, like so
```
app:customLayout="@layout/view_toggle_button"
```
