### ISSUE TITLE
Change selected color

### ISSUE THREAD

**Issue by edurocks** [savvyapps/ToggleButtonLayout#6]
How can I change programatically the selected color of the button? Thanks. Nice library.

**Comment by abdallahMurad** [comment]
+1

**Comment by Jawnnypoo** [comment]
Hey, thanks for brining this up. It can be done now in 1.1.0 of the library. 

```
toggleButtonLayoutText.selectedColor = ContextCompat.getColor(this, R.color.colorPrimary)
```

**Comment by edurocks** [comment]
Thanks brow. This is great.
________________________________
De: John Carlson <notifications@github.com>
Enviado: segunda-feira, 16 de julho de 2018 16:37
Para: savvyapps/ToggleButtonLayout
Cc: edurocks; Author
Assunto: Re: [savvyapps/ToggleButtonLayout] Change selected color (#6)


Hey, thanks for brining this up. It can be done now in 1.1.0 of the library.

toggleButtonLayoutText.selectedColor = ContextCompat.getColor(this, R.color.colorPrimary)
