### ISSUE TITLE
Graddle Sync failed

### ISSUE THREAD

**Issue by debjitk** [savvyapps/ToggleButtonLayout#7]
I know this is strange but when i include the library with ...
  implementation 'com.github.savvyapps:ToggleButtonLayout:1.1.0'

my graddle sync fails.

**Comment by Jawnnypoo** [comment]
Can you paste in here what the failure message is?

**Comment by debjitk** [comment]
implementation 'com.github.savvyapps:ToggleButtonLayout:1.1.0'

Gradle project sync message ...

12:04 AM	Gradle sync started

12:04 AM	Project setup started

12:04 AM	Gradle sync failed (28s 300ms)

**Comment by Jawnnypoo** [comment]
It should tell you why the Gradle sync failed if you go to the Build tab at the bottom. Something like this:
```
Failed to resolve: androidx.core:core-ktx:0.3121
Show in File
Show in Project Structure dialog
```

**Comment by Jawnnypoo** [comment]
Please try with 1.2.0 and we can reopen and try some more things if that doesn't resolve it.

**Comment by debjitk** [comment]
Same error with '1.2.0' as well. The build screen is showing ..

Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

CONFIGURE SUCCESSFUL in 8s

**Comment by Jawnnypoo** [comment]
Hm, from that, it sounds like it might be related to adding the Google Play Services plugin and not so much this library. Maybe confirm by removing this dependency from Gradle and seeing if you get the same issue?
